services:
 web:
  build: .
  entrypoint: sh -c "pip install -e /proj && cd example && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
  ports:
   - "8000:8000"
  depends_on:
   - postgres
   - redis
  environment:
   DATABASE_HOST: postgres
  tty: true
  stdin_open: true
  working_dir: /proj/
  user: test
  volumes:
   - ./:/proj/
   - ./pyenv:/home/test
 celery:
  build: .
  entrypoint: sh -c "pip install -e /proj && pip install redis && cd example && celery -A project worker --loglevel=info -n worker1"
  depends_on:
   - postgres
   - redis
  environment:
   DATABASE_HOST: postgres
  tty: true
  stdin_open: true
  working_dir: /proj/
  user: test
  volumes:
   - ./:/proj/
   - ./pyenv:/home/test
 redis:
  image: redis
 postgres:
  image: postgres:14-alpine
  ports:
   - "5432:5432"
  volumes:
   - ./db:/var/lib/postgresql/data
  environment:
   POSTGRES_PASSWORD: foobar
   POSTGRES_USER: pguser
   PGDATA: /var/lib/postgresql/data
   POSTGRES_HOST_AUTH_METHOD: md5
