# Generated by Django 2.2.4 on 2019-11-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_export_celery', '0003_exportjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportjob',
            name='email_on_completion',
            field=models.BooleanField(default=True, verbose_name='Send me an email when this export job is complete'),
        ),
    ]
