# Generated by Django 5.0.7 on 2024-07-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("import_export_celery", "0010_auto_20231013_0904"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportjob",
            name="resource_kwargs",
            field=models.JSONField(
                blank=True, default=None, null=True, verbose_name="Resource additional data parameters"
            ),
        ),
    ]
