# Generated by Django 3.2.25 on 2024-11-22 12:19

from django.db import migrations, models
import import_export_celery.utils


class Migration(migrations.Migration):

    dependencies = [
        ('import_export_celery', '0010_auto_20231013_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportjob',
            name='email_on_completion',
            field=models.BooleanField(default=import_export_celery.utils.get_export_job_email_on_completion, verbose_name='Send me an email when this export job is complete'),
        ),
    ]
