# Generated by Django 5.0.7 on 2024-07-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("import_export_celery", "0011_exportjob_resource_kwargs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportjob",
            name="queryset",
            field=models.JSONField(
                verbose_name="JSON list of pks to export or dict of queryset filters"
            ),
        ),
    ]
